version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Abc123!
      WORDPRESS_DB_NAME: carduccidemo
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: admin01
      MYSQL_DATABASE: carduccidemo
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Abc123!
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data: